### PR TITLE
FUSETOOLS2-2013: Provide command to run camel file with JBang

### PR DESCRIPTION
**Pull request by djelinek**
camelRunWithJBang

### CODE REVIEW

**Comment by djelinek** [comment]
WIP: need to provide tests

**Comment by djelinek** [comment]
currently there is UI test to check the presence of new command in command palette in case the camel file is opened

to test also the command execution itself I've created https://issues.redhat.com/browse/FUSETOOLS2-2018

**Review by apupier — APPROVED** [review]

**Review by apupier — COMMENTED** [review]
in the commit message, ther eis only FUSETOOLS2 without the issue number

**Comment by djelinek** [comment]
> in the commit message, ther eis only FUSETOOLS2 without the issue number

fixed! good catch, thanks

**Pull request merged**
